### ISSUE TITLE
Vendor classSet

### ISSUE THREAD

**Issue by prehnRA** [revelrylabs/revelry_core#31]
React will be spinning off classSet as a separate library. We should include that library and change our references over. Prevent future breakage and stop the deprecation warnings.

**Comment by jwietelmann** [comment]
I'm starting to question the utility of a lot of our convenience methods in our core mixins. The ones that actually make the most sense as component methods, like `classAdd`, `getPropsWithout`, and `getNormalizedChildren` I almost never see used outside of this gem. And the others (like `suitSet`) feel more like utility functions that I just happened to dump into the same bucket.

**Comment by prehnRA** [comment]
Either way: classSet is not going to be in React anymore and we use it in the framework and in a lot of application code. We need to either include classSet as a library explicitly, or convert our classSet code to use something else.
